CREATE DATABASE IF NOT EXISTS PortfolioTracker;
USE PortfolioTracker;

CREATE TABLE IF NOT EXISTS stocks (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    ticker VARCHAR(50) NOT NULL UNIQUE,
    quantity INT NOT NULL DEFAULT 1,
    buyPrice DECIMAL(10,2) NOT NULL,
    currentPrice DECIMAL(10,2) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);